### ISSUE TITLE
Feature Request: Multi Client / Dual Client

### ISSUE THREAD

**Issue by PatrickSantoZZ** [jsoctocat/BDO-Launcher#10]
Hey , its me again , 

its atm not possible to have Global Lab + EU/NA open but there is for sure a way to have 2 Clients open at the same time. sadly Nvidia Now dont support the normal Launcher yet.
Maybe you have an Idea / want to add this feature.

greetings~

**Comment by jsoctocat** [comment]
This isn't possible as it's limited by the anti-cheat, you can only have 1 instance of black desert open regardless of which region.
