### ISSUE TITLE
Missing BlackDesertEAC.exe

### ISSUE THREAD

**Issue by Person7557** [jsoctocat/BDO-Launcher#13]
![obraz](https://user-images.githubusercontent.com/95051528/143495289-b548cfb7-fba5-4344-886f-676b538364ce.png)

Hello Jsoctocat, as per title and screenshot, can you please help me get this application to work? Thanks.

**Comment by jsoctocat** [comment]
which region is this?

**Comment by Person7557** [comment]
Hold on, i might be just dumb, just found out i have 2 bdo folders...

**Comment by jsoctocat** [comment]
let me know if u ended up fixing it by using the correct folder so I can close this issue

**Comment by Person7557** [comment]
Right, so that issue is solved, but i encounter new problem.

Just ot make sure i do things right as there is no manual really. The Modules-x64 are supposed to replace files in the game folder?

when i launch the launcher now it screams that it lacks access to pad00000.meta and this..:

Details on invoking just-in-time (JIT) debugging
instead, the dialog box appears at the end of this message.

************** Exception text **************
System.UnauthorizedAccessException: Access denied to "C: \ Program Files (x86) \ Black Desert Online \ Paz \ pad00000.meta".
   at System.IO .__ Error.WinIOError (Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init (String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLong checkPath)
   at System.IO.FileStream..ctor (String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor (String path, FileMode mode)
   at Launcher.MainForm. <CheckVersion> d__4.MoveNext ()
--- End of stack trace from previous location where the exception occurred ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   in Launcher.MainForm. <MainForm_Load> d__5.MoveNext ()
--- End of stack trace from previous location where the exception occurred ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()


************** Loaded kits **************
mscorlib
    Assembly version: 4.0.0.0
    Win32-Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file: /// C: /Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Launcher
    Assembly version: 1.0.0.0
    Win32 version: 1.0.0.0
    CodeBase: file: /// C: / Program% 20Files% 20 (x86) /Black%20Desert%20Online/Launcher.exe
----------------------------------------
System.Windows.Forms
    Assembly version: 4.0.0.0
    Win32-Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly version: 4.0.0.0
    Win32-Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly version: 4.0.0.0
    Win32-Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly version: 4.0.0.0
    Win32-Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly version: 4.0.0.0
    Win32-Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly version: 11.0.0.0
    Win32 Version: 11.0.1.21818
    CodeBase: file: /// C: / Program% 20Files% 20 (x86) /Black%20Desert%20Online/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly version: 4.0.0.0
    Win32-Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly version: 4.0.0.0
    Win32-Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    Assembly version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_en_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
     Assembly version: 4.0.0.0
     Win32 Version: 4.8.4084.0 built by: NET48REL1
     CodeBase: file: /// C: /WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT debugging **************
To enable just in time (JIT) debugging, the .config file for this
application or computer (machine.config) must have
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with enabled
debugging.

For example:

<configuration>
     <system.windows.forms jitDebugging = "true" />
</configuration>

When JIT debugging is enabled, any unhandled exceptions
are sent to the JIT debugger registered on the computer
and are not supported in this dialog box.

**Comment by jsoctocat** [comment]
Don't extract the files to the game folder you have make a new folder and put the files there.

It request access to file pad00000.meta to grab the game version, the reason for this was some users requested to check if the game needs to be updated since this custom launcher doesn't mess with the game files; but the feature is pretty useless right now as I need to update this launcher to keep some features up to date, I will do that this weekend, regardless of that, this launcher should still launch the game.

If it's your first time downloading this, you need both Launcher-x64.zip and Modules-x64.zip, and have them both extracted to the same folder.

**Comment by Person7557** [comment]
Right. Downloading the game a-new, as it was bricked by me replacing some of original files with modules-x64.
So i can just keep it all in Launcher folder in that directory, and it should work?
let me test that out, and i'll let you know if its all good.

**Comment by Person7557** [comment]
So, i am still getting the same error with pad00000.meta on start up, and launcher does not accept OTP, says wrong login/pw/otp.
![obraz](https://user-images.githubusercontent.com/95051528/143498423-d1db50a1-2623-4593-866a-2069fdb3d44e.png)

**Comment by Person7557** [comment]
@jsoctocat Just want to confirm 3 things.
1. Error regarding access to Pad00000.meta can be dismissed, as i can just click continue and launcher starts, though its just annoying.
2. Does this application allow me to setup OTP in a way that i don't have to provide it on every start up, by simply entering the master password in that application?
3. I am in EU but i play on NA, can this cause this login issue?

**Comment by jsoctocat** [comment]
I will look into the pad0000.meta issue this weekend, please try again later could be because you are entered the otps wrong too many times u have to wait a bit. you can also confirm if it's that by log into the official launcher, which should be a more detailed message.

and yes, the whole purpose of this launcher is so that the user do not have to enter the OTP every single time by using the master password.

and no this wouldn't cause any issue unless you are on a region that's locked by the game publisher.

**Comment by Person7557** [comment]
So no more error on pad00000.meta this time. It also reports false error on user/pw/otp if you re-run the app too fast it seems. Logged in and then the game crashes unless i tick the 32bit version. Is that normal?
