### ISSUE TITLE
one out of three start ups are successful, but 64bit launcher crashes on start.

### ISSUE THREAD

**Issue by Person7557** [jsoctocat/BDO-Launcher#14]
Hello, as per title, when i start it up, 2/3 attempts end up with error
![obraz](https://user-images.githubusercontent.com/95051528/144282490-2888de7e-8581-4a0e-91c0-352141ae3e62.png)
and once it starts up, if it wasn't set to 32bit on launcher, the application crashes. Which is odd, as when i normally launch the program from PA launcher, it runs the 64bit version fine.
Can you look into this?

**Comment by jsoctocat** [comment]
when it crashes, does it show you the reason it crashes? or does the application just disappear?

**Comment by Person7557** [comment]
Sadly, just common windows application crashed. I will look into event viewer to see if i can find some traces, and i will see if there is something in bdo logs aswell.

**Comment by Person7557** [comment]
Right. so here are the game logs for launcher.

```
{"Date":"2021-12-01 20:21:47","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"convertEnumToString 함수에서 nullptr이 반환되었습니다." }
{"Date":"2021-12-01 20:21:47","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"convertEnumToString 함수에서 nullptr이 반환되었습니다." }
{"Date":"2021-12-01 20:21:47","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"--","ErrorString":"--","Log":"PetInfo _isFindThatMode를 저장하는데 실패 했습니다." }
{"Date":"2021-12-01 20:21:47","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"--","ErrorString":"--","Log":"PetInfo _isGetItemMode를 저장하는데 실패 했습니다." }
{"Date":"2021-12-01 20:21:47","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"convertEnumToString 함수에서 nullptr이 반환되었습니다." }
{"Date":"2021-12-01 20:21:47","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"convertEnumToString 함수에서 nullptr이 반환되었습니다." }
{"Date":"2021-12-01 20:21:47","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"sendBeginDelayExit : chracterSwitching(FALSE)" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x7508","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoPcLogout","ErrorString":"Player character is logging out.","Log":"Actor=>Index(3):(Client-PC/3/$0.0.0.0$):($UndefinedName$/0):logout:Reason(--(10101):[--])" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x7508","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoDevelopLog","ErrorString":"Development log!","Log":"Actor=>Index(3):(Client-PC/3/$0.0.0.0$):($UndefinedName$/0):logout completed:Reason(--(10101):[--])" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoPcLogout","ErrorString":"Player character is logging out.","Log":"Actor=>Index(8):(Client-PC/8/$0.0.0.0$):($UndefinedName$/0):logout:Reason(eErrNoUserRequestDisconnect(1199160933):[Did not connect.])" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoPcLogout","ErrorString":"Player character is logging out.","Log":"Actor=>Index(4):(Client-PC/4/$0.0.0.0$):($UndefinedName$/0):logout:Reason(eErrNoUserRequestDisconnect(1199160933):[Did not connect.])" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x7508","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoDevelopLog","ErrorString":"Development log!","Log":"Actor=>Index(8):(Client-PC/8/$0.0.0.0$):($UndefinedName$/0):logout completed:Reason(eErrNoUserRequestDisconnect(1199160933):[Did not connect.])" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"***** PAClientFramework::onDisconnectServer() GameVariable load ( eVariableStorageType_User )" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x7508","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoDevelopLog","ErrorString":"Development log!","Log":"Actor=>Index(4):(Client-PC/4/$0.0.0.0$):($UndefinedName$/0):logout completed:Reason(eErrNoUserRequestDisconnect(1199160933):[Did not connect.])" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"convertEnumToString 함수에서 nullptr이 반환되었습니다." }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"convertEnumToString 함수에서 nullptr이 반환되었습니다." }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"--","ErrorString":"--","Log":"PetInfo _isFindThatMode를 저장하는데 실패 했습니다." }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"--","ErrorString":"--","Log":"PetInfo _isGetItemMode를 저장하는데 실패 했습니다." }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"convertEnumToString 함수에서 nullptr이 반환되었습니다." }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"convertEnumToString 함수에서 nullptr이 반환되었습니다." }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"***** PAClientFramework::onDisconnectServer() GameVariable load ( eVariableStorageType_World )" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"***** PAClientFramework::onDisconnectServer() GameVariable load ( eVariableStorageType_Character )" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"***** PAClientFramework::onDisconnectServer() GameVariable load End" }
{"Date":"2021-12-01 20:21:50","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"Close Processor (8)" }
{"Date":"2021-12-01 20:21:51","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"Active Processor (4)" }
{"Date":"2021-12-01 20:21:51","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"PAProcessor_ClientLogin::activeProcess - start" }
{"Date":"2021-12-01 20:21:52","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"RoateRadarMode = FALSE" }
{"Date":"2021-12-01 20:21:52","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"Reconnect Fail From Reset" }
{"Date":"2021-12-01 20:21:52","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"setEndGame (not NotifyMessage) : 10" }
{"Date":"2021-12-01 20:21:52","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"setEndGame : 2" }
{"Date":"2021-12-01 20:21:52","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"setEndGame()" }
{"Date":"2021-12-01 20:21:52","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"--","ErrorString":"--","Log":"NorthAmericaGameClientAuthManager::close" }
{"Date":"2021-12-01 20:21:52","ThreadId":"0x074C","LogType":"00","ServiceLogLevel":"0","LogLevel":"1","ErrorNo":"eErrNoServiceLog","ErrorString":"Service log!","Log":"Terminating App: ExitInstance" }
```

and error from event viewer:

`Faulting application name: BlackDesert64.exe, version: 0.0.0.0, time stamp: 0x61a5d4b8
Faulting module name: BlackDesert64.exe, version: 0.0.0.0, time stamp: 0x61a5d4b8
Exception code: 0xc0000005
Error offset: 0x0000000000478a36
Faulting process id: 0x7a24
Faulting application start time: 0x01d7e6e8d3f8eac4
Faulting application path: C: \ Program Files (x86) \ Black Desert Online \ bin64 \ BlackDesert64.exe
Faulting module path: C: \ Program Files (x86) \ Black Desert Online \ bin64 \ BlackDesert64.exe
Report ID: ebde16fc-1883-4b42-a501-d3598e4f3516
Faulting package full name:
Application ID relative to the error package: `

and information in event viewer:

`Error package 2021420310238102757 type 4
Event Name: APPCRASH
Answer: Not available
CAB file ID: 0

Problem signature:
P1: BlackDesert64.exe
P2: 0.0.0.0
P3: 61a5d4b8
P4: BlackDesert64.exe
P5: 0.0.0.0
P6: 61a5d4b8
P7: c0000005
P8: 0000000000478a36
P9:
P10:

Included files:
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WER \ Temp \ WER9CCC.tmp.dmp
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WER \ Temp \ WER9D98.tmp.WERInternalMetadata.xml
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WER \ Temp \ WER9DA9.tmp.xml
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WER \ Temp \ WER9DB7.tmp.csv
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WER \ Temp \ WER9DD7.tmp.txt

These files can be accessed here:
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WER \ ReportArchive \ AppCrash_BlackDesert64.ex_235f5180d233e0f45dc3c485faf48a42c9b499e_e232bbec_3f863945-b30e-43b0-8929-108c212c3f

Analysis symbol:
Re-searching for a solution: 0
Report ID: ebde16fc-1883-4b42-a501-d3598e4f3516
Report status: 268435456
Package Hash Value: bfadc28f01ee63729c0d870fed8084e5
CAB GUID: 0 `

I also have the error report dump, so here it is:
`Version = 1
EventType = APPCRASH
EventTime = 132828601855435669
ReportType = 2
Consent = 1
UploadTime = 132828601859505449
ReportStatus = 268435456
ReportIdentifier = 3f863945-b30e-43b0-8929-108c212c3fb5
IntegratorReportIdentifier = ebde16fc-1883-4b42-a501-d3598e4f3516
Wow64Host = 34404
NsAppName = BlackDesert64.exe
AppSessionGuid = 00007a24-0001-0070-c4ea-f8d3e8e6d701
TargetAppId = W: 0006016acbb82ad630a65549dbf7333d968c0000ffff! 0000689f76447c6ac087456b325f56f0ee549939b19d! BlackDesert64.exe
TargetAppVer = 2021 // 11 // 30: 07: 37: 28! 18258de! BlackDesert64.exe
BootId = 4294967295
TargetAsId = 11351
UserImpactVector = 808452144
IsFatal = 1
EtwNonCollectReason = 1
Response.BucketId = bfadc28f01ee63729c0d870fed8084e5
Response.BucketTable = 4
Response.LegacyBucketId = 2021420310238102757
Response.type = 4
Sig [0] .Name = The name of the application
Sig [0] .Value = BlackDesert64.exe
Sig [1] .Name = Application version
Sig [1] .Value = 0.0.0.0
Sig [2] .Name = Application timestamp
Sig [2] .Value = 61a5d4b8
Sig [3] .Name = Name of the module with the error
Sig [3] .Value = BlackDesert64.exe
Sig [4] .Name = Module version with error
Sig [4] .Value = 0.0.0.0
Sig [5] .Name = Timestamp of the module with the error
Sig [5] .Value = 61a5d4b8
Sig [6] .Name = The exception code
Sig [6] .Value = c0000005
Sig [7] .Name = Exception offset
Sig [7] .Value = 0000000000478a36
DynamicSig [1] .Name = The version of the operating system
DynamicSig [1] .Value = 10.0.19043.2.0.0.256.48
DynamicSig [2] .Name = Locale ID
DynamicSig [2] .Value = 1045
DynamicSig [22] .Name = Additional Information 1
DynamicSig [22] .Value = 7dca
DynamicSig [23] .Name = Additional Information 2
DynamicSig [23] .Value = 7dca2fd3522fd9323138ab2009d4485c
DynamicSig [24] .Name = Additional Information 3
DynamicSig [24] .Value = 4bdd
DynamicSig [25] .Name = Additional Information 4
DynamicSig [25] .Value = 4bdd8ce280d91c5c237c6c6fcbb94e61
UI [2] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ BlackDesert64.exe
UI [3] = BlackDesert64.exe has stopped working.
UI [4] = Windows can search online for a solution to this problem.
UI [5] = Search online for a solution and close the program
UI [6] = Online search for a solution later and close the program
UI [7] = Close the application
LoadedModule [0] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ BlackDesert64.exe
LoadedModule [1] = C: \ WINDOWS \ SYSTEM32 \ ntdll.dll
LoadedModule [2] = C: \ WINDOWS \ System32 \ KERNEL32.DLL
LoadedModule [3] = C: \ WINDOWS \ System32 \ KERNELBASE.dll
LoadedModule [4] = C: \ WINDOWS \ WinSxS \ amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647 \ comctl32.dll
LoadedModule [5] = C: \ WINDOWS \ System32 \ ADVAPI32.dll
LoadedModule [6] = C: \ WINDOWS \ System32 \ msvcrt.dll
LoadedModule [7] = C: \ WINDOWS \ System32 \ sechost.dll
LoadedModule [8] = C: \ WINDOWS \ System32 \ RPCRT4.dll
LoadedModule [9] = C: \ WINDOWS \ System32 \ GDI32.dll
LoadedModule [10] = C: \ WINDOWS \ System32 \ win32u.dll
LoadedModule [11] = C: \ WINDOWS \ System32 \ gdi32full.dll
LoadedModule [12] = C: \ WINDOWS \ System32 \ msvcp_win.dll
LoadedModule [13] = C: \ WINDOWS \ System32 \ ucrtbase.dll
LoadedModule [14] = C: \ WINDOWS \ System32 \ USER32.dll
LoadedModule [15] = C: \ WINDOWS \ System32 \ IMM32.DLL
LoadedModule [16] = C: \ WINDOWS \ SYSTEM32 \ winmm.dll
LoadedModule [17] = C: \ WINDOWS \ System32 \ COMDLG32.dll
LoadedModule [18] = C: \ WINDOWS \ System32 \ combase.dll
LoadedModule [19] = C: \ WINDOWS \ System32 \ shcore.dll
LoadedModule [20] = C: \ WINDOWS \ System32 \ SHLWAPI.dll
LoadedModule [21] = C: \ WINDOWS \ System32 \ SHELL32.dll
LoadedModule [22] = C: \ WINDOWS \ System32 \ ole32.dll
LoadedModule [23] = C: \ WINDOWS \ System32 \ OLEAUT32.dll
LoadedModule [24] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ MSVCP140.dll
LoadedModule [25] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ VCRUNTIME140.dll
LoadedModule [26] = C: \ WINDOWS \ SYSTEM32 \ CRYPTBASE.DLL
LoadedModule [27] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ dbghelp.dll
LoadedModule [28] = C: \ WINDOWS \ System32 \ PSAPI.DLL
LoadedModule [29] = C: \ WINDOWS \ SYSTEM32 \ WSOCK32.dll
LoadedModule [30] = C: \ WINDOWS \ System32 \ WS2_32.dll
LoadedModule [31] = C: \ WINDOWS \ System32 \ WININET.dll
LoadedModule [32] = C: \ WINDOWS \ SYSTEM32 \ VERSION.dll
LoadedModule [33] = C: \ WINDOWS \ SYSTEM32 \ IPHLPAPI.DLL
LoadedModule [34] = C: \ WINDOWS \ SYSTEM32 \ d3d9.dll
LoadedModule [35] = C: \ WINDOWS \ SYSTEM32 \ kernel.appcore.dll
LoadedModule [36] = C: \ WINDOWS \ SYSTEM32 \ dwmapi.dll
LoadedModule [37] = C: \ WINDOWS \ SYSTEM32 \ windows.storage.dll
LoadedModule [38] = C: \ WINDOWS \ SYSTEM32 \ Wldp.dll
LoadedModule [39] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ d3dx9_43.dll
LoadedModule [40] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ XINPUT1_3.dll
LoadedModule [41] = C: \ WINDOWS \ System32 \ SETUPAPI.dll
LoadedModule [42] = C: \ WINDOWS \ System32 \ cfgmgr32.dll
LoadedModule [43] = C: \ WINDOWS \ System32 \ bcrypt.dll
LoadedModule [44] = C: \ WINDOWS \ SYSTEM32 \ d3d11.dll
LoadedModule [45] = C: \ WINDOWS \ SYSTEM32 \ dxgi.dll
LoadedModule [46] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ d3dx11_43.dll
LoadedModule [47] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ D3DCOMPILER_43.dll
LoadedModule [48] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ zlibwapi.dll
LoadedModule [49] = C: \ WINDOWS \ SYSTEM32 \ WINHTTP.dll
LoadedModule [50] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ CoherentUI64.dll
LoadedModule Rodzaje tłumaczeń
Tłumaczenie tekstu
Tekst źródłowy
auto_awesome
Język oryginału: angielski
3736 / 5000
Wyniki tłumaczenia
[51] = C: \ WINDOWS \ System32 \ WINTRUST.dll
LoadedModule [52] = C: \ WINDOWS \ System32 \ CRYPT32.dll
LoadedModule [53] = C: \ WINDOWS \ SYSTEM32 \ MSASN1.dll
LoadedModule [54] = C: \ WINDOWS \ WinSxS \ amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1348_none_91a2627ccc89e3fb \ gdiplus.dll
LoadedModule [55] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ portaudio_x64.dll
LoadedModule [56] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ AnselSDK64.dll
LoadedModule [57] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ bink2w64.dll
LoadedModule [58] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ VCOMP140.DLL
LoadedModule [59] = C: \ WINDOWS \ SYSTEM32 \ NETAPI32.dll
LoadedModule [60] = C: \ WINDOWS \ System32 \ NETUTILS.DLL
LoadedModule [61] = C: \ WINDOWS \ System32 \ bcryptPrimitives.dll
LoadedModule [62] = C: \ Program Files (x86) \ Black Desert Online \ EasyAntiCheat \ easyanticheat_x64.dll
LoadedModule [63] = C: \ WINDOWS \ SYSTEM32 \ profapi.dll
LoadedModule [64] = C: \ WINDOWS \ system32 \ uxtheme.dll
LoadedModule [65] = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ dbgcore.DLL
LoadedModule [66] = C: \ WINDOWS \ System32 \ MSCTF.dll
LoadedModule [67] = C: \ WINDOWS \ SYSTEM32 \ atlthunk.dll
LoadedModule [68] = C: \ WINDOWS \ SYSTEM32 \ textinputframework.dll
LoadedModule [69] = C: \ WINDOWS \ System32 \ CoreMessaging.dll
LoadedModule [70] = C: \ WINDOWS \ System32 \ CoreUIComponents.dll
LoadedModule [71] = C: \ WINDOWS \ SYSTEM32 \ ntmarta.dll
LoadedModule [72] = C: \ WINDOWS \ SYSTEM32 \ wintypes.dll
LoadedModule [73] = C: \ WINDOWS \ system32 \ mswsock.dll
LoadedModule [74] = C: \ WINDOWS \ system32 \ napinsp.dll
LoadedModule [75] = C: \ WINDOWS \ system32 \ pnrpnsp.dll
LoadedModule [76] = C: \ WINDOWS \ system32 \ wshbth.dll
LoadedModule [77] = C: \ WINDOWS \ system32 \ NLAapi.dll
LoadedModule [78] = C: \ WINDOWS \ SYSTEM32 \ DNSAPI.dll
LoadedModule [79] = C: \ WINDOWS \ System32 \ NSI.dll
LoadedModule [80] = C: \ WINDOWS \ System32 \ winrnr.dll
State [0] .Key = Transport.DoneStage1
State [0] .Value = 1
OsInfo [0] .Key = vermaj
OsInfo [0] .Value = 10
OsInfo [1] .Key = vermin
OsInfo [1] .Value = 0
OsInfo [2] .Key = verbld
OsInfo [2] .Value = 19043
OsInfo [3] .Key = ubr
OsInfo [3] .Value = 1348
OsInfo [4] .Key = versp
OsInfo [4] .Value = 0
OsInfo [5] .Key = arch
OsInfo [5] .Value = 9
OsInfo [6] .Key = lcid
OsInfo [6] .Value = 1045
OsInfo [7] .Key = geoid
OsInfo [7] .Value = 191
OsInfo [8] .Key = sku
OsInfo [8] .Value = 48
OsInfo [9] .Key = domain
OsInfo [9] .Value = 0
OsInfo [10] .Key = prodsuite
OsInfo [10] .Value = 256
OsInfo [11] .Key = ntprodtype
OsInfo [11] .Value = 1
OsInfo [12] .Key = platid
OsInfo [12] .Value = 10
OsInfo [13] .Key = sr
OsInfo [13] .Value = 0
OsInfo [14] .Key = tmsi
OsInfo [14] .Value = 221378274
OsInfo [15] .Key = osinsty
OsInfo [15] .Value = 1
OsInfo [16] .Key = iever
OsInfo [16] .Value = 11.789.19041.0-11.0.1000
OsInfo [17] .Key = portos
OsInfo [17] .Value = 0
OsInfo [18] .Key = ram
OsInfo [18] .Value = 32223
OsInfo [19] .Key = svolsz
OsInfo [19] .Value = 222
OsInfo [20] .Key = wimbt
OsInfo [20] .Value = 0
OsInfo [21] .Key = blddt
OsInfo [21] .Value = 191206
OsInfo [22] .Key = bldtm
OsInfo [22] .Value = 1406
OsInfo [23] .Key = bldbrch
OsInfo [23] .Value = vb_release
OsInfo [24] .Key = bldchk
OsInfo [24] .Value = 0
OsInfo [25] .Key = wpvermaj
OsInfo [25] .Value = 0
OsInfo [26] .Key = wpvermin
OsInfo [26] .Value = 0
OsInfo [27] .Key = wpbuildmaj
OsInfo [27] .Value = 0
OsInfo [28] .Key = wpbuildmin
OsInfo [28] .Value = 0
OsInfo [29] .Key = osver
OsInfo [29] .Value = 10.0.19041.1348.amd64fre.vb_release.191206-1406
OsInfo [30] .Key = buildflightid
OsInfo [30] .Value = 5b584c7e-5c25-4215-942e-69a22441362e
OsInfo [31] .Key = edition
OsInfo [31] .Value = Professional
OsInfo [32] .Key = ring
OsInfo [32] .Value = Retail
OsInfo [33] .Key = expid
OsInfo [34] .Key = fconid
OsInfo [35] .Key = containerid
OsInfo [36] .Key = containertype
OsInfo [37] .Key = edu
OsInfo [37] .Value = 0
FriendlyEventName = Operation stopped.
ConsentKey = APPCRASH
AppName = BlackDesert64.exe
AppPath = C: \ Program Files (x86) \ Black Desert Online \ bin64 \ BlackDesert64.exe
NsPartner = windows
NsGroup = windows8
ApplicationIdentity = 46B25269858B3DD1444C84BF6BCED9E5
MetadataHash = 2144509700 `

And my gut feeling is that it doesn't like AMD.

**Comment by jsoctocat** [comment]
is your system 32 or 64bit? could you double check by launching the game normally with the official launcher then open up your task manager, let me know if the game is running with 64.exe or 32.exe

**Comment by Person7557** [comment]
> 

System is 64bit win10 Polish Version.

When i want to launch from your launcher i only have success with 32bit version of the game.
screen:
![obraz](https://user-images.githubusercontent.com/95051528/144471906-8c75477f-2d9a-49c1-8365-2888bb01cc30.png)
but it works like crap (Lower fps, more frequent crashes, etc).

When i start it from PA's crappy launcher it works in 64bit no problems.

screen:
![obraz](https://user-images.githubusercontent.com/95051528/144472168-7b3c8900-cae7-422b-bb1a-73918154421e.png)

**Comment by jsoctocat** [comment]
thank you, I will take a look at this over the weekend

**Comment by jsoctocat** [comment]
this issue happened because the game is installed on your C drive which requires admin privilege to launch (some files require admin privilege to access), I don't know why it doesn't crash with the 32bit version though; The fix is actually already there, I just have that part of the code commented out since it was never needed for me, I will add an option to run the game as admin so this issue won't happen again for you.

**Comment by jsoctocat** [comment]
Updated the launcher to 1.1.4, and it should address this issue, could you test it and let me know if it's fixed for you?

**Comment by Person7557** [comment]
Deleted old one as it was spitting errors, downloaded 1.1.4.

Successful launch on first attempt. Thank you for packing it up neatly in one folder aswell.

Seems to be working as intended. :)

**Comment by Person7557** [comment]
Deleted old one as it was spitting errors, downloaded 1.1.4.

Successful launch on first attempt. Thank you for packing it up neatly in one folder aswell.

Seems to be working as intended. :)
