### ISSUE TITLE
Check for game updates still doesn't work, and check for launcher update in 1.1.4 says newer version is available.

### ISSUE THREAD

**Issue by Person7557** [jsoctocat/BDO-Launcher#15]
as per title, check for update still shows the error on start, i'm just guessing at this point, but i have a feeling that you wrote it as =.net 4.0 while it should be >=
Launcher update option i guess its not checking with whats the current release string? as it was saying that 1.1.3 is now available.

From my point of view, its doing more than enough as it is now, so maybe just remove those two functions and that way its less confusing for money users. :)

**Comment by jsoctocat** [comment]
Yes, I forgot to change the launcher version on the server side, that should be fixed now, thanks for letting me know.

As for the game update, could you post the error it's showing? the function is working for me.

**Comment by Person7557** [comment]
same spaghetti code as i reported earlier, here is a piece of it and screenshot.
![obraz](https://user-images.githubusercontent.com/95051528/145621073-b5d7f0e8-c8a3-48c9-acc5-0aa000377d67.png)

'''
************** Tekst wyjątku **************
System.UnauthorizedAccessException: Odmowa dostępu do ścieżki „C:\Program Files (x86)\Black Desert Online\Paz\pad00000.meta”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   w System.IO.FileStream..ctor(String path, FileMode mode)
   w Launcher.MainForm.<CheckVersion>d__4.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Launcher.MainForm.<MainForm_Load>d__5.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Zestawy załadowane **************
mscorlib
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Launcher
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Black%20Desert%20Online/Launcher/Launcher.exe
----------------------------------------
System.Windows.Forms
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Wersja zestawu: 13.0.0.0
    Wersja Win32: 13.0.1.25517
    CodeBase: file:///C:/Program%20Files%20(x86)/Black%20Desert%20Online/Launcher/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
'''

i hope you don't mind me not translating it to english this time, as its simply error version of kit: 4.0 vs windows kit: 4.8 or 13.0.1 etc.

**Comment by jsoctocat** [comment]
this is an issue with the launcher lacking privilege to access the game version file, it should be fixed if you run the launcher in admin

**Comment by Person7557** [comment]
> this is an issue with the launcher lacking privilege to access the game version file, it should be fixed if you run the launcher in admin
> 
> right click on the launcher, Run As Administrator

marked it to run as admin, and ye, no more error.
