### ISSUE TITLE
Launcher no longer works?

### ISSUE THREAD

**Issue by Person7557** [jsoctocat/BDO-Launcher#17]
Hello Jsoctocat.
For some unknown reason the launcher no longer works for me.
I though that perhaps the password or OTP got corrupted, so i just re-entered password,
![obraz](https://user-images.githubusercontent.com/95051528/165856647-1c5ebcaf-36c7-413f-9a0d-938b0b39d3de.png)
I attempted to login with blank OTP.
![obraz](https://user-images.githubusercontent.com/95051528/165856783-1e4343c8-62f5-482b-b433-0b47f904d95d.png)
i enter the code but it ain't happy.
![obraz](https://user-images.githubusercontent.com/95051528/165856818-095b9c5c-65cb-40be-851a-be519f5588a5.png)
![obraz](https://user-images.githubusercontent.com/95051528/165856834-a0061446-a5bf-49a9-951d-ce403c0ca44e.png)
so i attempted to re-register the OTP, but that did not help either, still same errors.

Can you please check if yours is still functional? And if it is, could you please assist in getting mine back to operations?
Thank you very much.

**Comment by jsoctocat** [comment]
could you login via the official launcher? I just tested it on my end and it's still working fine.

**Comment by Person7557** [comment]
I did, via official launcher its also fine, so i am confused as well.
Where can i find the settings to be saved? I guess it might be currupted.

**Comment by Person7557** [comment]
hm. maybe i messed up with delay and its simply unstable. i'll have to check if going back to default latency resolves the issue.

**Comment by Person7557** [comment]
![obraz](https://user-images.githubusercontent.com/95051528/165897708-26eb73fd-3ceb-41ef-a4b9-735f3c7675e0.png)
Oh. Fuck you PA.

**Comment by Person7557** [comment]
![obraz](https://user-images.githubusercontent.com/95051528/165897793-989952c4-1e1d-4016-a33f-2006b2598756.png)
Oh. That explains it.

**Comment by Person7557** [comment]
No nevermind, changed the password, still the same.
![obraz](https://user-images.githubusercontent.com/95051528/165898048-34a03e15-90e3-4276-962c-4655f4915433.png)
