### ISSUE TITLE
Feature Request: Start official launcher if patch required

### ISSUE THREAD

**Issue by moeffju** [jsoctocat/BDO-Launcher#2]
Really love the launcher - so much, in fact, that every Wednesday after maintenance, I start it 3 or 4 times and fail to connect to the game, before realizing that I forgot to patch it.

Actually doing the patching would probably be too painful, but if there's any way to detect that a patch is required and either notify the user or even launch the official launcher, that would be nice :)

**Comment by jsoctocat** [comment]
The requested feature has been added in version 1.0.9

**Comment by moeffju** [comment]
🙏🏼
