### ISSUE TITLE
Launcher issues

### ISSUE THREAD

**Issue by Person7557** [jsoctocat/BDO-Launcher#20]
Hello Jsoctocat, my launcher stopped working today after maintenance. I attempted to check files to make sure that its not my bdo folder, game starts fine from official launcher, attempted to update launcher, now i get BrowserForm pop up and display the steps, but it either fails to provide the OTP or simply says wrong OTP/password in the end. Replacing the 1.1.5 version with current 1.1.5 version shows that there is a new launcher version available, but none on the website. Is there one on the way, or is something not working as it should? Thank you.

**Comment by Person7557** [comment]
![obraz](https://github.com/jsoctocat/BDO-Launcher/assets/95051528/49d0a6d3-e429-40cc-9d50-eac7dae90af9)

**Comment by jsoctocat** [comment]
could it be the same as this issue? 

https://github.com/jsoctocat/BDO-Launcher/issues/17#issuecomment-1112999896

**Comment by Person7557** [comment]
Oh i forgot to mention, i did time sync before writing, as i do remember that from previous issue, but no, it did not resolve the issue for me. Also, is this supposed to show up?

![obraz](https://github.com/jsoctocat/BDO-Launcher/assets/95051528/e0e5b38d-a1ba-4505-8d05-1062413c3de4)

**Comment by Person7557** [comment]
Or any of this? 
![obraz](https://github.com/jsoctocat/BDO-Launcher/assets/95051528/12a1f64a-846f-4228-a04d-35c8d3fd73b2)
![obraz](https://github.com/jsoctocat/BDO-Launcher/assets/95051528/675fd8e0-e3eb-4700-873d-f19295095a7e)

**Comment by Person7557** [comment]
I just ran double check on Backup OTP code and seems like its incorrect, I'll restart it and see if it works then.

**Comment by jsoctocat** [comment]
> Or any of this? ![obraz](https://user-images.githubusercontent.com/95051528/281485216-12a1f64a-846f-4228-a04d-35c8d3fd73b2.png) ![obraz](https://user-images.githubusercontent.com/95051528/281485343-675fd8e0-e3eb-4700-873d-f19295095a7e.png)

Yes, these pop-ups are intended because it is possible for a CAPTCHA to appear, and this was the simplest way to address such an issue.

The version check should not pop up though, I will take a look at it in an hour.

**Comment by Person7557** [comment]
Seems like it fails to enter OTP either way for me. Strange.

**Comment by Person7557** [comment]
Just managed to get the launcher to login me in on 1.1.3 version

**Comment by jsoctocat** [comment]
have you checked with the official launcher? the delay can be edited inside AuthenticationServiceProvider.cs 

`            // wait for server response data
          delayCounter = 1000;
          do {
              await Task.Delay(delayCounter);
              delayCounter += 50;
          } while (CustomResourceRequestHandler.ResponseData == null && delayCounter < 10000);`

I will change the OTP to be generated from UTC time that gets fetched from worldtimeapi today

**Comment by jsoctocat** [comment]
I updated the launcher to input the OTP when the OTP appears rather than at the start of the launching process, let me know if the change fixes issue #20

**Comment by Person7557** [comment]
> I updated the launcher to input the OTP when the OTP appears rather than at the start of the launching process, let me know if the change fixes issue #20

Thank you, i will test it within an hour and let you know how it works.

**Comment by Person7557** [comment]
It works nicely now. One suggestion would be to make an option to select visible or not visible form, as i prefered the lack of things popping up, would be great if you could let me know if i can just enable/disable that in one line of the code

**Comment by Breetlez** [comment]
I upgraded to lastest version and it works fine. only thing i want to mention is every time i press start game it shows the BrowserForm window then it disappear and start the game. i wish if this window are hidden like previous version

**Comment by jsoctocat** [comment]
In version 1.1.5 I changed CefSharp.OffScreen to CefSharp.WinForms so that a browserform opens up and shows the login process, the reason for the change was because there is a chance of running into this 

![ss](https://github.com/jsoctocat/BDO-Launcher/assets/42134925/a87bec86-8039-4a94-a714-33a301c86263)

The launcher would get stuck waiting for the captcha to be completed before moving onto the next login step, therefore, I made the change.

I will check to see if it's possible to hide the window but most likely the solution would be automatically minimize the window at the start

**Comment by jsoctocat** [comment]
Release [1.1.6a](https://github.com/jsoctocat/BDO-Launcher/releases/tag/1.1.6a) will minimize the BrowserForm at the start

**Comment by Person7557** [comment]
> In version 1.1.5 I changed CefSharp.OffScreen to CefSharp.WinForms so that a browserform opens up and shows the login process, the reason for the change was because there is a chance of running into this
> 
> ![ss](https://user-images.githubusercontent.com/42134925/281670229-a87bec86-8039-4a94-a714-33a301c86263.png)
> 
> The launcher would get stuck waiting for the captcha to be completed before moving onto the next login step, therefore, I made the change.
> 
> I will check to see if it's possible to hide the window but most likely the solution would be automatically minimize the window at the start

I've never once encountered this, that's why i did not see any point in that form to pop up for me.
