### ISSUE TITLE
Error messages for Visual Studio

### ISSUE THREAD

**Issue by Guazy** [jsoctocat/BDO-Launcher#22]
I downloaded this launcher to try it out but downloaded visual studio to make it an EXE file. When I started the project, I received a lot of errors and I could not convert it to an exe file.

The designer for this file could not be displayed because none of the classes in this file could be designed. The designer examined the following classes in the file: BrowserForm --- Unable to design base class 'System.Void'.

and I have more error messages.

Adding an updated exe file to this project may be useful to many users. Thank you.

**Comment by jsoctocat** [comment]
check out the release page
https://github.com/jsoctocat/BDO-Launcher/releases

I update the executable every time there is a code change
