### ISSUE TITLE
Issue with anticheat changes

### ISSUE THREAD

**Issue by guala01** [jsoctocat/BDO-Launcher#23]
Today anticheat was changed from EAC to xigincode, removing the necessity to start EAC process with the game. At the moment it seems to be throwing an error due to it not finding the .exe.

**Comment by jsoctocat** [comment]
yeah I just fixed it, I'm pushing my changes right now

**Comment by jsoctocat** [comment]
Release [1.1.8](https://github.com/jsoctocat/BDO-Launcher/releases/tag/1.1.8) should address this issue
