### ISSUE TITLE
Error -1007 after/during login in BrowserForm

### ISSUE THREAD

**Issue by AkechiShiro** [jsoctocat/BDO-Launcher#26]
![image](https://github.com/jsoctocat/BDO-Launcher/assets/14914796/a893d2db-d18d-42a9-80dc-94a9a0e3d9fc)
![image](https://github.com/jsoctocat/BDO-Launcher/assets/14914796/381f7408-bc99-4d3b-adc2-75e4eb0323b5)

Any clue or any idea what to do to further debug ?

**Comment by jsoctocat** [comment]
that means the account has not yet accepted the terms of service, you need to accept the terms of service from official launcher before able to use this one

**Comment by AkechiShiro** [comment]
Is it possible to accept them from the website ?

As the launcher is full black since I'm on Linux I have no idea how I can accept those terms without seeing the accept button

Maybe the only is to have a Windows machine on which I accept them.

**Comment by jsoctocat** [comment]
you might be able to accept the TOS from the [launcher URL ](https://account.pearlabyss.com/en-US/Launcher/Login/)

**Comment by AkechiShiro** [comment]
Thanks !

**Comment by AkechiShiro** [comment]
I tried to but when logging in it is saying to me that I cannot login in that region, it must be default on other than the EU/NA region.

**Comment by AkechiShiro** [comment]
Logging in works, but I don't see any terms to accept

**Comment by jsoctocat** [comment]
are you using a new account? that's never started the game before? I think the terms page only shows up when you click start game button

**Comment by AkechiShiro** [comment]
No it's a very old account I used first in 2021, I did reactivate the account when I logged in first, it was scheduled to be deleted in 2026.

**Comment by jsoctocat** [comment]
can you play the game when logging in from the official?

**Comment by AkechiShiro** [comment]
I haven't tried this as the launcher on Linux is full black, the bug has been fixed but the fix upstream hasn't been released in Proton or any official Wine release yet.

**Comment by jsoctocat** [comment]
Closed due to inactivity
