### ISSUE TITLE
xignCode, the great come back.

### ISSUE THREAD

**Issue by wildtruc** [jsoctocat/BDO-Launcher#27]
The launcher reach for EAC bin in the path. But BDO is now using XignCode again. 
This, really need a fixe.

**Comment by jsoctocat** [comment]
it was fixed 2 weeks ago [1.1.8 ](https://github.com/jsoctocat/BDO-Launcher/releases/tag/1.1.8)

**Comment by wildtruc** [comment]
I saw that lately yesterday.
Thanks for you work !

**Comment by wildtruc** [comment]
Solved.
