### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by Lunatory** [jsoctocat/BDO-Launcher#28]
I've wiped my bdo launcher folder and redownloaded the runtime, playwright (2.0.0) and launcher (2.0.2) yet I still get prompted for an update on every launch. Did you forget to bump the version to 2.0.2 in wherever the launcher checks for its current version vs online version, or perhaps package the wrong .exe? The launcher itself states 2.0.0 still as well when open.

**Comment by jsoctocat** [comment]
well good to know someone is using that feature!

I have replaced the binaries that updated the version string to 2.0.2 for both Windows and Linux. You can download them [here](https://github.com/jsoctocat/BDO-Launcher/releases/tag/2.0.2)
