### ISSUE TITLE
Account Authentication Failed

### ISSUE THREAD

**Issue by ManchiSoul** [jsoctocat/BDO-Launcher#30]
Hello

I dont have any issues when launching the game through your BDO-launcher, but when i press start in-game i get message 

![authentication](https://github.com/jsoctocat/BDO-Launcher/assets/45339747/e1054cc1-0fa2-49b5-8f80-95ac9a1b00d5)

I dont think there is login information problems, if so i should have got it through bdo launcher.

**Comment by ManchiSoul** [comment]
I am gonna close this for now till i investigate more, (Reboot PC, Router, etc...)

**Comment by jsoctocat** [comment]
cuz you need to update your game lol @ManchiSoul
