### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pepega404** [jsoctocat/BDO-Launcher#31]
hello i got this error "Playwright firefox 1438 is missing"

![fire](https://github.com/jsoctocat/BDO-Launcher/assets/165848013/b3a1f043-6340-45e0-8c1e-d6fb3b813254)

**Comment by thanatossystem** [comment]
I'm having the same issue with the pre-built version from the latest release.

**Comment by jsoctocat** [comment]
@thanatossystem download the playwright module from [2.0.0](https://github.com/jsoctocat/BDO-Launcher/releases/tag/2.0.0)

If on linux -> Linux.x64-playwright.zip 

If on windows -> Windows.x64-playwright.zip

**Comment by thanatossystem** [comment]
I apologize, didn't read that properly. Thanks for the help 👍

**Comment by Agalamagugu** [comment]
I actually do not get it, is this something you are supposed to build together? im just an average User and i do not really understand the error message
![image](https://github.com/user-attachments/assets/4aab7f6a-7374-4739-b769-5470980df4d1)

I downloaded the Windows.x64-playwright.zip but what am i supposed to do with it, there are no instructions anywhere

**Comment by jsoctocat** [comment]
> I actually do not get it, is this something you are supposed to build together? im just an average User and i do not really understand the error message ![image](https://private-user-images.githubusercontent.com/175481889/348466533-4aab7f6a-7374-4739-b769-5470980df4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MTM2NzAsIm5iZiI6MTcyMDkxMzM3MCwicGF0aCI6Ii8xNzU0ODE4ODkvMzQ4NDY2NTMzLTRhYWI3ZjZhLTczNzQtNDczOS1iNzY5LTU0NzA5ODBkZjRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QyMzI5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjAzMjMwOTFlYjE2MTkwNzllZTU4MDFkNGM0MTZiZDM2NDNmMDg0ODE1NmRhMGZlYjgxNTkzNjk1MjJhYTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qFO4F1j_GTsrEek5jNkBxtnMJAdC1mSEJjiJg_ZFyiY)
> 
> I downloaded the Windows.x64-playwright.zip but what am i supposed to do with it, there are no instructions anywhere

Got it, I will update the instruction to be more clear.

You extract the content of the zip file into the same folder as the launcher

**Comment by Agalamagugu** [comment]
Thank you very much for your answer, i tried everything except copying the whole folder and now it works!
