### ISSUE TITLE
Error when launching game and password has not been changed in a while

### ISSUE THREAD

**Issue by moeffju** [jsoctocat/BDO-Launcher#5]
This morning I got an error with the launcher unable to get the playToken. After retrying a few times, I used the official launcher, which after login popped up a window complaining that my password hadn't been changed in a while (I believe 90 days?) and offered to change it or defer for 3 months.

Aside from the frankly silly thinking about IT Security on PA's part - I use a 32+ character password through a password manager and yet I still need to relogin every time, manually input OTP, even if the PC is registered etc. which is super annoying - it would be nice if the alternative launcher also gracefully handled this and either showed the message, automatically dimissed it, or at least notify the user to run the official launcher.

I am expecting this to happen with a bunch of accounts now since it's ~90 days from the game transfer.

**Comment by jsoctocat** [comment]
I have not gotten that error, will look into it once I do.

**Comment by jsoctocat** [comment]
I have pushed a change (1.1.2a) that should address this issue, tested it on the global lab version, because I haven't gotten the error on na/eu version I will leave this issue up until I can confirm that this issue has been resolved.

**Comment by Person7557** [comment]
I can confirm its still happening.

**Comment by jsoctocat** [comment]
1.1.4 should address this issue
