### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by PatrickSantoZZ** [jsoctocat/BDO-Launcher#7]
Is it maybe possible to add a update function / client check? i dont know if the update data is available when they have a maintenance but would be a nice feature to predownload the update and be able to directly play when servers are online again.

greetings~

**Comment by jsoctocat** [comment]
There are both client check and launcher check options available from version 1.0.9 and up.

The weekly update data is not available to download until the maintenance is close to being over.

**Comment by PatrickSantoZZ** [comment]
okay thank you for awnsering. o/
