### ISSUE TITLE
dont get playtoken at all.

### ISSUE THREAD

**Issue by PatrickSantoZZ** [jsoctocat/BDO-Launcher#8]
![image](https://user-images.githubusercontent.com/20726844/122054644-2746f300-cde8-11eb-80b7-09be0c87bb9d.png)
hey tested it now with 4 different clients on EU and i dont get an playtoken at all

edit:
password & mail are correct , iam able to login on the website and with official launcher without problems. 
no otp

**Comment by jsoctocat** [comment]
is it possible to start the game on the official launcher? playtaken is the last step before starting the game, it's after u have successfully logged in.

**Comment by PatrickSantoZZ** [comment]
![image](https://user-images.githubusercontent.com/20726844/122057020-78f07d00-cdea-11eb-9ade-5922f2537b5f.png)
yup its possible to start the game with the official launcher.

**Comment by PatrickSantoZZ** [comment]
okay nvm starting the launcher => closing it => starting again worked. maybe something went wrong in the background.

**Comment by jsoctocat** [comment]
cool, I tested it on my end just now and I was able to log in smoothly, I will leave this issue up for the next 12 hours, if you don't encounter the issue again I will then close it.
