### ISSUE TITLE
account authentication failed

### ISSUE THREAD

**Issue by linux858** [jsoctocat/BDO-Launcher#9]
I got this error after press start button in-game at main menu screen of bdo.

**Comment by jsoctocat** [comment]
your client might be out of date

**Comment by linux858** [comment]
I am . i just update the game yesterday with the main launcher. your launcher works well but after i changed the region from eu to na in your launcher i got this error in both region now

**Comment by jsoctocat** [comment]
ok, I was able to reproduce this issue, working on it now, thanks for letting me know

**Comment by jsoctocat** [comment]
version 1.1.3 should address this issue, feel free to open up this issue if doesn't.
